### ISSUE TITLE
Where always returns empty data set

### ISSUE THREAD

**Issue by sivailangos** [arthurkushman/buildsqlx#59]
Simple where condition not working in PostgreSQL

````
qDb := db.Table("roles").Select("role").Where("role", "=", "general")
````
above snippet always returns null

**Comment by arthurkushman** [comment]
`Where` clause must definitely return:
```
*DB
```
struct, but if u need the result of a query, u should use `.Get()` function:
```
.Where("role", "=", "general").Get()
```
which returns `[]map[string]interface{}` 

Can you show an example of creating a new connection? Like this:
```
var db = NewDb(NewConnection("postgres", "host=postgres user=postgres dbname=postgres password=postgres sslmode=disable"))
```

PS all tests passed in Actions, so it can't be non-working.
https://github.com/arthurkushman/buildsqlx/actions/runs/114480117

**Comment by sivailangos** [comment]
````
var db = buildsqlx.NewDb(buildsqlx.NewConnection("postgres", "user=postgres dbname=postgres password=postgres sslmode=disable"))

qDb := db.Table("roles").Select("role").Where("role", "=", "general")

res, err := qDb.Get()

if err != nil {
	fmt.Println(err)
}

return c.JSON(&fiber.Map{
	"status": true,
	"data":   res,
})
````

I am using gofiber framework to send JSON response

**Comment by arthurkushman** [comment]
Hi, what I've done to test your example and abstract away an application that uses it from buildsqlx, is that:
- created new dir for go project
- set-up there a simple docker-compose file with content:
```yaml
db:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
```
then executed the code:
```go
package main

import (
	"fmt"
	"github.com/arthurkushman/buildsqlx"
)

func main() {
	var db = buildsqlx.NewDb(buildsqlx.NewConnection("postgres", "host=127.0.0.1 user=postgres dbname=postgres password=postgres sslmode=disable"))

	qDb := db.Table("pg_roles").Select("rolname").Where("rolname", "=", "postgres")

	res, err := qDb.Get()

	if err != nil {
		fmt.Println(err)
	}

	fmt.Println(res)
}
```

1-st thing that u should check is the errors in console, because there is no `roles` default pg schema, but `pg_roles`, also there is no column `role`, but `pg_roles`. 
It works perfectly fine on my local machine, with docker instance and after `docker-compose up` successful run.

**Comment by sivailangos** [comment]
@arthurkushman I've kept database as `postgres` just for example on above code snippet. There is a `roles` table in my database. Is there a way I can see actual SQL query formed from builder?

**Comment by arthurkushman** [comment]
> @arthurkushman I've kept database as `postgres` just for example on above code snippet. There is a `roles` table in my database. Is there a way I can see actual SQL query formed from builder?

Sure @sivailangos u can add `.Dump` or `.Dd` at any chain call: https://github.com/arthurkushman/buildsqlx/blob/bcead85cce9ff0c65ccab9c8aae885b6e14ef11f/builder.go#L495

**Comment by sivailangos** [comment]
Still same issue, below is screenshot of raw query,
![image](https://user-images.githubusercontent.com/17606063/98241527-16501c80-1f91-11eb-9969-6f471035dd8b.png)

Below is code snippet
![image](https://user-images.githubusercontent.com/17606063/98241892-99717280-1f91-11eb-99a5-3f7dfb277e15.png)

Am I missing anything? If I remove where condition then it works perfectly

**Comment by arthurkushman** [comment]
It seems that u are correct about this behaviour with Where clause, when it is used with string values, unfortunately native sql.Query() function can't do this conversion - https://github.com/arthurkushman/buildsqlx/blob/bcead85cce9ff0c65ccab9c8aae885b6e14ef11f/factory.go#L40

though it has been built by code correctly - https://github.com/arthurkushman/buildsqlx/blob/bcead85cce9ff0c65ccab9c8aae885b6e14ef11f/factory.go#L83

It seems like there is a need of recode the Query behaviour, but I suppose not with something `fmt.Sprintf` which will live the holes in security, but the alternative ways like .Scan for example seems even more difficult and non-resembling to the code-base. 

May be u can offer an elegant solution? But as for me I don't see at this moment anything except for those two.

**Comment by arthurkushman** [comment]
Hi, good news incorrect bindings on string values had been fixed - https://github.com/arthurkushman/buildsqlx/releases/tag/v0.7.5
All tests passed + 1 for Where clause only
https://github.com/arthurkushman/buildsqlx/runs/1367896340?check_suite_focus=true

**Comment by sivailangos** [comment]
> Hi, good news incorrect bindings on string values had been fixed - https://github.com/arthurkushman/buildsqlx/releases/tag/v0.7.5
> All tests passed + 1 for Where clause only
> https://github.com/arthurkushman/buildsqlx/runs/1367896340?check_suite_focus=true

It works now!!! Thanks for quick turn around!
