### ISSUE TITLE
How can I rollback all query in nested funtion

### ISSUE THREAD

**Issue by hzjux001** [arthurkushman/buildsqlx#84]
How can I rollback all query in nested funtion
just like

err = sqlxdb.InTransaction(func() (interface{}, error) {
err =func1(sqlxdb){
do some query
}
if err !=nil{
return nil,err
}

 err =func2(sqlxdb){
       do some query
 }
 if err !=nil{
    return nil,err
 }  
})

when func2 return err but can't rollback query in func1

**Comment by Deme94** [comment]
Hello, it doesn't work for me

return m.Db.InTransaction(func() (interface{}, error) {
		err := m.Db.Table("users").Insert(map[string]interface{}{
			"username": u.Username,
			"email":    strings.ToLower(u.Email),
			"password": u.Password,
			"nick":     nick,
		})
		if err != nil {
			return nil, err
		}

		// if this is the first user, admin role is assigned
		count, err := m.Db.Table("users").Count()
		if err != nil {
			return nil, err
		}
		if count == 1 {
			// get first user id
			res, err := m.Db.Table("users").Select("id").First()
			if err != nil {
				return nil, err
			}
			idUser := int(res["id"].(int64))
			
			// get admin role id
			res, err = m.Db.Table("roles").Select("id").Where("name", "=", "admin").
				First()
			if err != nil {
				fmt.Println(err)
				return nil, err
			}
			idAdminRole := int(res["id"].(int64))

			// Assign role to user
			err = m.UpdateRoles(idUser, idAdminRole)
			if err != nil {
				return nil, err
			}
		}

		return nil, nil
	})
	
My first insert is applied even if the next queries fail. Am I missing something?

**Comment by Deme94** [comment]
I have checked your code, and I don't really know how you rollback the queries made inside that function you pass by parameter to InTransaction()

This is how tx works:
```
 // Get a Tx for making transaction requests.
    tx, err := db.BeginTx(ctx, nil)
    if err != nil {
        return err
    }
    // Defer a rollback in case anything fails.
    defer tx.Rollback()

    // Update the album inventory to remove the quantity in the order.
    _, err = tx.ExecContext(ctx, "UPDATE album SET quantity = quantity - ? WHERE id = ?",
        quantity, albumID)
    if err != nil {
        return err
    }

    // Commit the transaction.
    if err = tx.Commit(); err != nil {
        return fail(err)
    }
```
As you can see, the queries are made on the tx reference. That's the only way to rollback a query. 

Your code:

```
        txn, err := r.Sql().Begin()
	if err != nil {
		return err
	}

	res, err := fn()
	if err != nil {
		errTxn := txn.Rollback()
		if errTxn != nil {
			return errTxn
		}
		return err
	}
```

**Comment by hzjux001** [comment]
err = sqlxdb.InTransaction(func() (interface{}, error) {
			uuidstr := uuid.NamespaceDNS.String()
			rid,err:=sqlxdb.Table("customform_main_7").InsertGetId((map[string]interface{}{
				"unitid":uuidstr,
				"unitname":uuidstr,
				"status":0,
				"system_id":1,
				"rowindex":0,
				"createuser_id":1,
			}))
			if err!=nil{
				return nil,err
			}else{
				fmt.Println(rid)
			}
			return nil,errors.New("test error")
})

why after return nil,errors.New("test error"),but sqlxdb not rollback,the record still inserted into db

**Comment by arthurkushman** [comment]
> ```
> 	err = sqlxdb.InTransaction(func() (interface{}, error) {
> 		uuidstr := uuid.NamespaceDNS.String()
> 		rid,err:=sqlxdb.Table("customform_main_7").InsertGetId((map[string]interface{}{
> 			"unitid":uuidstr,
> 			"unitname":uuidstr,
> 			"status":0,
> 			"system_id":1,
> 			"rowindex":0,
> 			"createuser_id":1,
> 		}))
> 		if err!=nil{
> 			return nil,err
> 		}else{
> 			fmt.Println(rid)
> 		}
> 		return nil,errors.New("test error")
> ```
> 
> })
> 
> why after return nil,errors.New("test error"),but sqlxdb not rollback,the record still inserted into db

Hi, thx for mentioning this problem, this was a naive implementation and should be re-coded properly, code-base will be vastly changed - will let u know when end up with all this.

**Comment by arthurkushman** [comment]
https://github.com/arthurkushman/buildsqlx/releases/tag/v0.8.9
