### ISSUE TITLE
Using an existing sql.Db connection

### ISSUE THREAD

**Issue by dvaldivia** [arthurkushman/buildsqlx#87]
I see `Conneciton` wraps a `sql.Db`, my application already has an stablished sql.Db connection, is it ok to add an additional contructor to `Connection` or `NewDb` to re-use that connection? if so I can send the PR

**Comment by arthurkushman** [comment]
> I see `Conneciton` wraps a `sql.Db`, my application already has an stablished sql.Db connection, is it ok to add an additional contructor to `Connection` or `NewDb` to re-use that connection? if so I can send the PR

Hi, sure - u can call it `NewConenctionFromDb` or smth like that.

**Comment by DannyHinshaw** [comment]
Came here for this! This would definitely help give the package a little more flexibility 👍 

@dvaldivia is this still on your radar? If not I can take it over (no pressure) 🙂

**Comment by arthurkushman** [comment]
https://github.com/arthurkushman/buildsqlx/releases/tag/v0.8.7
