### ISSUE TITLE
wherenull 

### ISSUE THREAD

**Issue by hzjux001** [arthurkushman/buildsqlx#94]
The condition "WhereNull" cannot coexist with a "where" condition, so it is not possible to achieve a requirement like sqlxdb.Table(tablename).Select(".*").Where("id", "=", uintrecid).WhereNull("deleted_at").

The code in factory.go is as follows:

```
if len(r.whereBindings) > 0 {
    clauses += composeWhere(r.whereBindings, r.startBindingsAt)
} else {
    // std without bindings todo: change all to bindings
    clauses += r.where
}
```

**Comment by arthurkushman** [comment]
Hi, pls try to use `And*/Or*` statements, like f.e.: `AndWhereNull`, e.g. this stmt works fine for me:
```go
res, err := db.Table(PostsTable).Select("title").Where("user_id", "=", int64(3)).AndWhereNull("post").Get()
```

PS stmts started on Where* is just designed to start from where clause.
