### ISSUE TITLE
Is it possible to type the insert statements and select statements

### ISSUE THREAD

**Issue by TiLopes** [arthurkushman/buildsqlx#96]
I read that this library does not use structs to use less CPU, however if I wanted to use a struct/type would it be possible?
I'm new to Go and would like to have certain parts be strictly typed.

**Comment by arthurkushman** [comment]
Thank u for the question (sorry for it takes so long), yes now u can use any structs to be parsed for getting the sql-query results whether it will be a single row or multiple - https://github.com/arthurkushman/buildsqlx/releases/tag/v1.0.0

PS README docs also has been changed accordingly
